### ISSUE TITLE
Player tools clipping into blocks

### ISSUE THREAD

**Issue by Watchdog82** [UltimateDoge5/PhantomShapes#6]
![Screenshot 2024-11-09 211809](https://github.com/user-attachments/assets/69eed672-e33f-4198-891c-e867fcf54033)
![Screenshot 2024-11-09 211832](https://github.com/user-attachments/assets/c60b38c1-2ef6-498d-9c99-07ef7f440f81)

Tools also disappear while in water

**Comment by UltimateDoge5** [comment]
Thanks for the feedback! I'll try to investigate this bug in a while. Could you also tell me what Minecraft version are you on?
