### ISSUE TITLE
Shapes not being Hidden after changing size and position

### ISSUE THREAD

**Issue by MonkeeBoy64-On-Discord** [UltimateDoge5/PhantomShapes#7]
Versions
Minecraft 1.21.3 Fabric and PhantomShapes 3.0.5

the mod doesn't seem to hide previous shapes after changing its size or position

![image](https://github.com/user-attachments/assets/80ace748-f28b-4655-9361-bbce13b3871e)

![image](https://github.com/user-attachments/assets/3ed49b85-ae6c-4cd8-a14a-4fb15d6c69d8)

![image](https://github.com/user-attachments/assets/63986d12-a400-43a7-a33a-a943d2d3dfbe)

sorry if the images aren't the most coherent things, this is my first bug report.

**Comment by MonkeeBoy64-On-Discord** [comment]
also there is a wierd small circle in the middle

**Comment by MonkeeBoy64-On-Discord** [comment]
which i am assuming is related

**Comment by UltimateDoge5** [comment]
Thanks for the feedback! Thank you for including pictures, they do really help. I've been able to replicate this bug and the fixed version should be available soon.

**Comment by UltimateDoge5** [comment]
Version 1.1.4 with the bug fixed is now available for download on modrinth.
