### ISSUE TITLE
Crash upon finishing a shape

### ISSUE THREAD

**Issue by BlindTwig** [UltimateDoge5/PhantomShapes#8]
**Basic information**
Minecraft 1.21.1, mod version 1.1.1.

**Describe the bug**
The client crashes the moment the final block of a shape is placed, and continues to do so if trying to re-open the world. Client settings were all default.

**Crash Log**
First log is upon placing the final block, second log is trying to re-open the world.
[crash-2024-12-05_13.33.49-client.txt](https://github.com/user-attachments/files/18028077/crash-2024-12-05_13.33.49-client.txt)
[crash-2024-12-05_13.38.00-client.txt](https://github.com/user-attachments/files/18028087/crash-2024-12-05_13.38.00-client.txt)

**Comment by UltimateDoge5** [comment]
Thanks for the feedback! This seems like an easy fix and shouldn't take long. I see you are on the 1.21.1 version of Minecraft. I'll try to backport the fix to that version. Meanwhile, a temporary fix for you would be to just disable the shape rendering in the settings via the modmenu.

**Comment by UltimateDoge5** [comment]
Turns out, that due to the changes I have done in the versions later, this bug does not exist in the newer ones. So the backport was enough. The ported version is now on [modrinth](https://modrinth.com/mod/phantomshapes/version/T4VmN3PZ). If the bug still somehow persists, reopen the issue. Enjoy.
